// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-RY6A0dHwhKGYdHhLDj999Y-EARQ98k',
    appId: '1:953860646592:web:190ec7dace0be1c0576f25',
    messagingSenderId: '953860646592',
    projectId: 'chat-app-733af',
    authDomain: 'chat-app-733af.firebaseapp.com',
    storageBucket: 'chat-app-733af.firebasestorage.app',
    measurementId: 'G-KV2E1FCG2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAejKrahs-sGrcw_7p7z5pDgy5cc0bka9s',
    appId: '1:953860646592:android:94135b1a6784441a576f25',
    messagingSenderId: '953860646592',
    projectId: 'chat-app-733af',
    storageBucket: 'chat-app-733af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByEp8W0hJoK13-E-dIBTMiwDkXGcFxRMY',
    appId: '1:953860646592:ios:ea9eb76fdb663e78576f25',
    messagingSenderId: '953860646592',
    projectId: 'chat-app-733af',
    storageBucket: 'chat-app-733af.firebasestorage.app',
    iosClientId: '953860646592-dhj35r42trmufg9u408ud79tonfegot2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByEp8W0hJoK13-E-dIBTMiwDkXGcFxRMY',
    appId: '1:953860646592:ios:ea9eb76fdb663e78576f25',
    messagingSenderId: '953860646592',
    projectId: 'chat-app-733af',
    storageBucket: 'chat-app-733af.firebasestorage.app',
    iosClientId: '953860646592-dhj35r42trmufg9u408ud79tonfegot2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz-RY6A0dHwhKGYdHhLDj999Y-EARQ98k',
    appId: '1:953860646592:web:310fe968e1f15fc3576f25',
    messagingSenderId: '953860646592',
    projectId: 'chat-app-733af',
    authDomain: 'chat-app-733af.firebaseapp.com',
    storageBucket: 'chat-app-733af.firebasestorage.app',
    measurementId: 'G-26KKS3YHCV',
  );
}
